#!/bin/bash
# Package index: 0=root, 1=gibuu, 2=roottuple, 3=buuinput
PKGS=(root gibuu roottuple buuinput)
PKG_URLS=(
  "https://root.cern.ch/download/root_v6.38.04.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz"
  "https://github.com/kvtsang/GiBUU.git"
  "https://github.com/kvtsang/GiBUU-RootTuple.git"
  "https://gibuu.hepforge.org/downloads?f=buuinput2025.tar.gz"
)
PKG_FILES=(
  "root_v6.38.04.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz"
  ""
  ""
  "buuinput2025.tar.gz"
)
PKG_CHECKSUMS=(
  "af241e9b4aeb93f6fedfb5d360b31494"
  ""
  ""
  "6d8d5c432008831ddeea38e7b91550ee"
)

die() {
  echo "$@" >&2
  exit 1
}

pkg_idx() {
  local name="$1" idx
  for idx in "${!PKGS[@]}"; do
    [[ "${PKGS[$idx]}" == "$name" ]] && echo "$idx" && return
  done
  die "Unknown package: $name"
}

git_clone() {
  local url="$1"
  local dest="$2"
  local branch="${3:-main}"
  git clone --branch "$branch" --depth 1 "$url" "$dest" \
	  || die "Fail to clone $url"
}

fetch() {
  local name="$1"
  local idx=$(pkg_idx "$name")
  local url="${PKG_URLS[$idx]}"
  local file="${PKG_FILES[$idx]}"

  wget -N -O "$file" "$url" || die "Fail to download $name ($file)"
}

help() {
  cat <<-_EOF
$PROGRAM: install GiBUU to a user directory

Note
====
The patched GiBUU is installed to the directory where the script is executed.
The script is intended to be used in container.

Usage
=====
$PROGRAM download [package] [branch]
    Download packages (all by default). branch defaults to 'main'.
    Packages: root, gibuu, roottuple, buuinput

$PROGRAM checksum [package]
    Run md5sum on downloaded files (all by default).

$PROGRAM unpack
    Unzip / untar download files to current directory.

$PROGRAM build
    Build GiBUU.

$PROGRAM install [DEST]
    Install GiBUU.x to DEST directory.

_EOF
}

download() {
  local branch="${2:-main}"
  local target="${1:-all}"

  if [[ "$target" == "all" ]]; then
    fetch root
    git_clone "${PKG_URLS[1]}" release "$branch"
    git_clone "${PKG_URLS[2]}" libraries/RootTuple "$branch"
    fetch buuinput
  else
    case "$target" in
      root)      fetch root ;;
      gibuu)     git_clone "${PKG_URLS[1]}" release "$branch" ;;
      roottuple) git_clone "${PKG_URLS[2]}" libraries/RootTuple "$branch" ;;
      buuinput)  fetch buuinput ;;
      *)         die "Unknown package: $target. Use: root, gibuu, roottuple, buuinput" ;;
    esac
  fi
}

checksum() {
  local target="${1:-all}"
  local failed=0

  if [[ "$target" == "all" ]]; then
    pkgs=("root" "buuinput")
  else
    pkgs=("$target")
  fi

  for name in "${pkgs[@]}"; do
    local idx=$(pkg_idx "$name")
    local file="${PKG_FILES[$idx]}"
    local expected="${PKG_CHECKSUMS[$idx]}"

    [[ -z "$file" || -z "$expected" ]] && die "No checksum for $name"
    actual=$(md5sum "$file" | cut -d' ' -f1)
    if [[ "$actual" != "$expected" ]]; then
      echo "FAIL: $name ($file)" >&2
      echo "  expected: $expected" >&2
      echo "  actual:   $actual" >&2
      failed=1
    else
      echo "OK: $name ($file)"
    fi
  done

  [[ $failed -ne 0 ]] && die "Checksum verification failed"
}

unpack() {
  echo "Unpacking ROOT ..."
  tar zxf "${PKG_FILES[0]}" || die "Fail to unpack ROOT"

  echo "Setting up GiBUU ..."

  mkdir -p gibuu || die "Fail to create gibuu/"
  cd gibuu || die "Fail to enter gibuu/"

  tar zxf ../"${PKG_FILES[3]}" || die "Fail to unpack GiBUU"

  exit 0
}

build() {
  source root/bin/thisroot.sh

  cd release || die "release/ directory not found"

  mkdir -p objects/LIB/lib \
  && make -j $(nproc) buildRootTuple \
  && make -j $(nproc) withROOT=1
}

install() {
  DEST=${1:-./}
  echo "Copying GiBUU.x to $DEST"

  mkdir -p "$DEST" || die "Fail to create $DEST"
  cp release/objects/GiBUU.x "$DEST" || die "Fail to copy GiBUU.x"

  exit 0
}

usage() {
  echo "$PROGRAM download [package] [branch] | checksum [package] | unpack | build | install [DEST] | help"
}

PROGRAM="${0##*/}"

case "$1" in
  download) shift; download "$@" ;;
  checksum) shift; checksum "$@" ;;
  unpack)   shift; unpack "$@" ;;
  build)    shift; build "$@" ;;
  install)  shift; install "$@" ;;
  help|-h)  shift; help ;;
  usage|--usage|-u) shift; usage ;;
  *)        usage; exit 1 ;;
esac
